-- Status Rodeo schema export, generated 2026-10-06 from the live database.
-- Covers tables, foreign keys, RLS, and policies.
-- Table grants are not included: anon and authenticated hold the Supabase default
-- grants on both tables.
-- Requires the auth schema (present in every Supabase project) for auth.users.

create table public.profiles (
  user_id uuid not null primary key,
  created_at timestamp with time zone default now(),
  username text not null unique,
  display_name text not null
);

create table public.statuses (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  content text not null,
  visibility text not null default 'public'::text,
  created_at timestamp with time zone default now()
);

alter table public.profiles
  add constraint profiles_user_id_fkey
  foreign key (user_id) references auth.users(id);

alter table public.statuses
  add constraint statuses_user_id_fkey
  foreign key (user_id) references auth.users(id);

alter table public.statuses
  add constraint statuses_user_id_fkey1
  foreign key (user_id) references public.profiles(user_id);

alter table public.profiles enable row level security;
alter table public.statuses enable row level security;

create policy "Public profiles are viewable"
  on public.profiles for select to public
  using (true);

create policy "Public statuses are viewable"
  on public.statuses for select to public
  using (visibility = 'public'::text);

create policy "Users can create their own statuses"
  on public.statuses for insert to authenticated
  with check (((select auth.uid() as uid) = user_id));
